### PR TITLE
feat: add brand filtering

### LINKED ISSUE #278: Add the UI to allow to filter by brand
### What

- [ ] While documenting Robotoff, I realized that brand filtering was possible https://robotoff.openfoodfacts.org/api/v1/questions/random?lang=fr&insight_types=category&server_domain=api.openfoodfacts.org&count=10&value_tag=en:bcaa&country=en:france&brands=ironmaxx
- [ ] This means we could create brand specific views, useful to get producer to validate data about their products, or to ensure a brand is well completed after an import

### PR DESCRIPTION
**Pull request by alexfauquette**
The question components was a bit messy because it has to synchronize:
 - the buffer of questions
 - the URL parameters
 - the interface

So I propose to split the logic as follow:

The filters are implemented by a distinct component `<QuestionFilter />` which does these three tasks described below. 
This new component is considered as a big input component by `<QuestionView/>` This new "input" component is in charge of maintaining the questionBuffer full, whereas `<QuestionView />` is in charge of the global interface and the annotations.

The workflow is simplified, to display fewer inputs, and prevent inconsistencies between the filters and the URL parameters.

In the new workflow, you add/modify filters by opening a form. When you're okay, click on "apply". It refreshes the list of questions and the URL. In my opinion, updating filters with a button is easier to deal with and so prevents some bugs.

To do

- [x] Think about better wording
- [x] use translation files instead of hard codded strings

### CODE REVIEW

**Comment by alexfauquette** [comment]
After a night of thinking, This is not a good solution.

I plan to let the responsibility of the buffer of questions to the main component, such as the filter component can be reused in other pages

**Review by teolemon — APPROVED** [review]
I absolutely love it ❤️. The last nail in the coffin would be to use the autosuggest API: https://github.com/openfoodfacts/api-documentation/issues/40

**Comment by alexfauquette** [comment]
The autosuggest API is not usable for robotoff, because if I search `organ` the result will be `Organic` bu robotoff needs `en:organic`.

If it only returns english translation, we can try to always add `en:`  before the world, but it seems to be dirty trick.

Do we have a list of the labels detected by robotoff?

**Comment by teolemon** [comment]
No, we don't. We can drop autosuggest for now. It would probably be nice to evolve the suggest.pl API to return a tag optionally

**Pull request merged**
