### PR TITLE
allow to scroll an make crop rectangle more visible

### PR DESCRIPTION
**Pull request by alexfauquette**
Some improvement from slack

### CODE REVIEW

**Comment by VaiTon** [comment]
Where can I view the changes?

**Comment by alexfauquette** [comment]
You can see the test environment here : https://deploy-preview-140--gifted-lalande-686eef.netlify.app/table

You can also press "Details" in the netlify "Deploy preview ready!" line. Then you need to modify the url to acces the "table" page

For now it seems that robotoff is in difficulty so hunger game does not work

**Comment by VaiTon** [comment]
Just a question, can we add the link to the router, so that we have an easy access?

**Review by VaiTon — APPROVED** [review]

**Comment by alexfauquette** [comment]
I do not understand, you mean to add into the menu the link to "table" ?

For now we did not since it's not an easy game. So we just put the link to the game in the documentation, such that people who found this game also had access to the documentation

**Comment by teolemon** [comment]
I'm merging @alexfauquette @VaiTon 
For the link, @VaiTon it's deliberate since this game is extremely complicated, and used to annotate for a ML model

**Pull request merged**
