### PR TITLE
feat: clean version of the interactive nutrition table game

### PR DESCRIPTION
**Pull request by alexfauquette**
I restart my PR with cleaner code

My TODO : 

- [x] keep a history of the seen product (their code, and if the user skipped it or fill the form, or removed the image)
- [x] add a button to unselect the image if no nutrition information is available
- [x] randomize the product presented to the user
- [x] translate more nutrients some vitamins are missing from my translation
- [x] Allows to annotate only one product by putting its code in the url
- [ ] fetch already filled nutriments
- [x] adapt the unit selector (for example, viamins can be in micro grams) @teolemon do you have a son for that ?
- [x] Allows to rotate the image

### CODE REVIEW

**Comment by alexfauquette** [comment]
The history

image

**Comment by alexfauquette** [comment]
https://www.loom.com/share/bc80813ffb4a43d08f1679b2e8057d32

**Comment by teolemon** [comment]
@alexfauquette @VaiTon conflicts after the updates

**Comment by alexfauquette** [comment]
Does not seems to be important conflicts. I will do it this week-end

**Comment by alexfauquette** [comment]
That's good, I rebased on master. I also add the storage of seen products (validated, skipped or deleted) such that if you refresh the page you do not see all the products you already skipped

@teolemon I think it is good to go on master and be deployed

**Pull request merged**
