### PR TITLE
design: new expanded menu on desktop

### PR DESCRIPTION
**Pull request by astagi**
image

image

### CODE REVIEW

**Comment by teolemon** [comment]
😍

**Comment by VaiTon** [comment]
@astagi what about separators?

**Comment by astagi** [comment]
> @astagi what about separators?

@VaiTon I removed separators on expanded version. If they're needed, we could think of implementing a multilevel menu

**Comment by VaiTon** [comment]
Maybe we could place them to the right side?

**Comment by astagi** [comment]
> Maybe we could place them to the right side?

@VaiTon I prefer the left side, on the right side we have the annotations section.

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
