### PR TITLE
Make Insights responsive

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by VaiTon** [comment]
@astagi could you provide some screenshots. I don't understand what did you make responsive. :-)

**Comment by astagi** [comment]
image
image

@VaiTon

**Review by raphael0202 — APPROVED** [review]

**Comment by raphael0202** [comment]
I've tested it locally, seems good to me, thanks!

**Comment by astagi** [comment]
You're welcome @raphael0202

**Pull request merged**
